services:
  - type: web
    name: tomato-disease-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: TRANSFORMERS_CACHE
        value: /var/cache/huggingface
